### ISSUE TITLE
Tall cards

### ISSUE THREAD

**Issue by mattstauffer** [tightenco/nova-package-development#1]
I have a lot of cards that are taller than the enforced 150px for 1/2 and 2/3 cards.

I've solved it two different ways. One, I've forced the height with manual CSS (which breaks the dashboard flow):

![image](https://user-images.githubusercontent.com/151829/44932764-b74d4800-ad34-11e8-95eb-d106411f58b8.png)

And two, i've added internal scrollers:

![image](https://user-images.githubusercontent.com/151829/44932758-ad2b4980-ad34-11e8-88ba-7addf8c9572e.png)

Any thoughts/preferences/other tricks/etc.?

**Comment by alexbowers** [comment]
My thoughts, bearing in mind its 4am, are perhaps that how something like this should work is that the card acts as a summary or preview, but if there is more than X amount of data, that should action you towards a dashboard view with the complete dataset on it.

For example, your GA most-visited pages would show the top 5 pages, and have a link to a Google Analytics dashboard to view them all, and you'll be able to do more on that page, like sort, filter etc.

Otherwise it'd be pretty easy to hit 20, 30, 50 results within time and have a crazy tall card that doesn't fit the rest of the page.

**Comment by themsaid** [comment]
Yes I think a card may show just a few records with a link to view full details.

**Comment by ovvessem** [comment]
Agree with @alexbowers and @themsaid. I think a card should be seen as a summary of data with a link to view the extend of it.

**Comment by mattstauffer** [comment]
I think these are really great points. Thanks everyone!
