### ISSUE TITLE
Nova Breadcrumb Package

### ISSUE THREAD

**Issue by dillingham** [tightenco/nova-package-development#48]

**Comment by bernhardh** [comment]
Any news from this? Especially if you use the tab package, you will get lost very easy. For example:

![image](https://user-images.githubusercontent.com/642292/47100120-16104780-d237-11e8-8459-b1e8973105aa.png)

Which article do I edit right now? Nobody knows, since the information is only available in the first tab "Allgemeines".

**Comment by dillingham** [comment]
Not sure I see the relationship between tabs and breadcrumbs 

This package is not in production 

Feel free to build it though :)

**Comment by bernhardh** [comment]
The relationship would be, that I don't see where I am, when not on the "main" tab, because only on main tab you would see the title/name of the article. If there would be a breadcrumb in the way you suggested, I would see "Home > Articles > $title > Edit" ("Home > Articles > My cool Article > Edit") and I would know on every tab, which article I am editing right know.

If I find out, how to do it, I will probably make a package for it.

**Comment by dillingham** [comment]
Ah I see what you mean, well there is CustomToolbar vue components that can be overridden 

https://github.com/laravel/nova-issues/issues/786#issuecomment-427952057

**Comment by bernhardh** [comment]
I known, there is `custom-index-toolbar` and `custom-detail-toolbar`, but no `custom-edit-toolbar`, so that will not work ;)

**Comment by dillingham** [comment]
there's a header one too 🤷‍♂️

**Comment by bernhardh** [comment]
>there's a header one too

what does this mean?

**Comment by nasrulhazim** [comment]
Is it possible to have https://github.com/davejamesmiller/laravel-breadcrumbs to be implement in Nova? try to use in Nova, but no luck at the moment. 

```php 
<?php 

use Laravel\Nova\Nova;

// Dashboard
Breadcrumbs::for('nova.index', function ($trail) {
	$trail->push(__('Dashboard'), url(Nova::path()));
}); 

Breadcrumbs::for('nova.', function ($trail, $view) {
	$trail->parent('nova.index');
	$trail->push(uriToTitle($view), url($view));
}); 
```

This is so far how I configure, but no luck display the breadcrumb correctly, Nova rely on VueJS. So I'm not really sure how to implement in VueJs from Laravel Breadcrumb package.

**Comment by chris-ware** [comment]
Fellow developers, I give to you Breadcrumbs:
https://packagist.org/packages/chris-ware/nova-breadcrumbs

**Comment by scaventum** [comment]
> Fellow developers, I give to you Breadcrumbs:
> https://packagist.org/packages/chris-ware/nova-breadcrumbs

Great package!

Is it possible to make breadcrumb run through relationship using this package? e.g. 1 character has many stories:

therefore the breadcrumb will be `home \ characters \ character-01 \ story-01 \ ...` or something similar
