### ISSUE TITLE
[WIP] Menu package

### ISSUE THREAD

**Issue by tomhatzer** [tightenco/nova-package-development#5]
I'm currently working on a nova menu package, that has spatie/menu (spatie/laravel-menu) integration. So you basically just have to do a `Menu::build(NovaMenu::getTree(), 'NovaMenu::buildMenu')` in the frontend and everything will be done by the NovaMenu and the spatie Package.

Creating menus is already working, I'm currently working on the menu items (using an already existing [vue component](https://github.com/holiber/sl-vue-tree) that I'm customizing) - with drag and drop support.

Demo of adding new menus:
![nova-menu-animation](https://user-images.githubusercontent.com/3952168/45040075-66f02600-b065-11e8-9fc5-42c92e9623e8.gif)

If anyone has any recommendations based on the gif, please go ahead and tell me 😀

**Comment by monaye** [comment]
Looking great! 
Maybe instead of showing the menu list in select, why don't you just use the regular list => detail UI/UX?
So, in the future, you can easily add an action button to each menu, where you can hide menu, sort, delete.   
Just an idea 😄 
![sample](https://user-images.githubusercontent.com/1147313/45067058-4a52fd00-b0fc-11e8-9594-d3d82af8dbc1.png)

**Comment by tomhatzer** [comment]
I had the wordpress menu style in mind, where you select the menu from above and then customize the menu items below it. So you can have multiple separate menus on the website, wherever you like 😃 Hiding menu items is already on the list, as this is a functionality that the vue component already offers, deleting menu items will be added to this too.

**Comment by willmkt** [comment]
Any updates on this package?

**Comment by dillingham** [comment]
abandoned
