### ISSUE TITLE
Nova Form Tool Package 

### ISSUE THREAD

**Issue by dillingham** [tightenco/nova-package-development#63]

**Comment by dillingham** [comment]
```php
<?php

namespace App\Nova\Forms;

class Support extends NovaFormController
{
    function create()
    {
        return [
            ID::make()->sortable(),

            Text::make('Name')
                ->sortable()
                ->rules('required', 'max:255'),

            Text::make('Email')
                ->sortable()
                ->rules('required', 'email', 'max:254')
                ->creationRules('unique:users,email')
                ->updateRules('unique:users,email,{{resourceId}}'),
        ];
    }

    public function store($request)
    {
        \App\User::create($request->all());

        return response()->json([
            'redirect' => back()
        ]);
    }
}
```

**Comment by dillingham** [comment]
Some how registering this dynamically & allowing other package developers to do the same 🔥

**Comment by toonvandenbos** [comment]
Hi @dillingham, I think we just published something similar to your request. Have a look at [Nova Page](https://novapackages.com/packages/whitecube/nova-page) ;)

Feel free to request features or updates on our [repository](https://github.com/whitecube/nova-page). It's still a work in progress, but some of our websites are already running on it.

**Comment by anderly** [comment]
I'm thinking of something like `ActionForm` which would basically support routing to a new screen to render an Action's fields, etc. This could be used to integrate with external reporting tools like Crystal Reports, SSRS, etc. or for sending to a 3rd-party service, etc.

The new form is necessary because there could be a large number of fields needed as parameters.

I'm going to take a stab at this. As I see it, we need something like the Create Form field display but using an Action's fields.

In many cases, I need this from an existing Resource detail screen. For example, a way to run a Crystal Report under a given resource context.

**Comment by chrispage1** [comment]
Hey @dillingham, did you get a solution to this?

I'm interested to use for a bulk import tool.
